version: '1.0.0.{build}'
image: Visual Studio 2019
configuration: Release
platform:
    - x64
branches:
  only:
    - master

environment:
    qt: 5.14.2
    msvc: msvc2017
    vs: C:\"Program Files (x86)"\"Microsoft Visual Studio"\2019\Community\VC\Auxiliary\Build
    QTDIR: C:\Qt\5.14.2\msvc2017_64
    QT_Include: C:\Qt\5.14.2\msvc2017_64\include;C:\Qt\5.14.2\msvc2017_64\include\QtWidgets;C:\Qt\5.14.2\msvc2017_64\include\QtGui;C:\Qt\5.14.2\msvc2017_64\include\QtANGLE;C:\Qt\5.14.2\msvc2017_64\include\QtWebSockets;C:\Qt\5.14.2\msvc2017_64\include\QtNetwork;C:\Qt\5.14.2\msvc2017_64\include\QtCore;C:\Qt\5.14.2\msvc2017_64\bin
    ProjectName: GenshinTianLiBallentClient
    ProJectExeName: GenshinTianLiBallentClient
    MyProjectDir: C:\projects\GenshinTianLiBallentClient
    #OpenCvDir: C:\projects\opencv\
    #OpenCvUrl: https://github.com/GengGode/opencv450Release/releases/download/v1.0/Release.zip

    APPVEYOR_RDP_PASSWORD: cL#!E9#M3L9%R7og
skip_tags: true

init:
   #- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
    # - ps: $env:TIME_STRING=(get-date -UFormat "%Y%m%d%a").ToString()
    # 
    # # download opencv:
    # - mkdir %OpenCvDir%
    # - appveyor DownloadFile %OpenCvUrl%
    # - 7z x ./*.zip -y -o%OpenCvDir%
    # - rm -f ./*.zip
    # - dir %OpenCvDir%
    # - cd %MyProjectDir%\%ProjectName%\
    # - 7z x ./resource.rar -y -o%MyProjectDir%\%ProjectName%\
    
on_finish:
    #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  
before_build: 
    - set PATH=%PATH%;%OpencvDir%\include;%OpencvDir%\x64\vc15\staticlib;C:\projects\opencv\bin;%QTDIR%\bin;%QT_Include%
    - set VC_IncludePath=%OpencvDir%\include;%OpencvDir%\x64\vc15\staticlib;C:\projects\opencv\bin;%QTDIR%\bin;%QT_Include%
    - call %QTDIR%\bin\qtenv2.bat
    - call %vs%\vcvars64.bat x64

build_script:
    - env
    - dir %QTDIR%
    - dir %QTDIR%\include
    #- MSBuild %MyProjectDir%TianLiInstallationPackage\TianLiInstallationPackage.vcxproj
    - cd %MyProjectDir%\%ProjectName%

    #- qmake -tp vc GenshinImpact_AutoMap.pro
    #- qmake -o Makefile GenshinImpact_AutoMap.pro
    #- nmake /K 
    #- cd..
    # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    
    #- MSBuild %ProjectName%.sln /p:Configuration=Release /p:Platform=x64 
    #- qmake
    #- nmake
    
after_build:
    # copy include and source code files
    - mkdir %MyProjectDir%\x64\build\
    - cd %MyProjectDir%\x64\Release\
    - ren *.exe TianLi_Map.exe 
    - copy %MyProjectDir%\x64\Release\TianLi_Map.exe %MyProjectDir%\x64\build\
    
    - cd %MyProjectDir%\x64\build\
    - windeployqt TianLi_Map.exe -release

    - echo %APPVEYOR_BUILD_VERSION% >version.tag
    - 7z a %ProJectExeName%.7z %MyProjectDir%\x64\build\*
    
    #- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
    
    - appveyor PushArtifact version.tag
    - appveyor PushArtifact %ProJectExeName%.7z
    
deploy:
    - provider: GitHub
      description: '$(APPVEYOR_PROJECT_SLUG): $(ProJectExeName) $(APPVEYOR_BUILD_VERSION)' 
      auth_token:
         secure: G/Fzf0bGIhqqt+XvsC5AXrZVNs3atGU7XCzJxqiUZEwOxoZrjxk87ENI/OitnXCo
      draft: false
      tag: $(APPVEYOR_BUILD_VERSION)
      force_update: true
      on:  
        APPVEYOR_REPO_TAG: false

notifications:
  - provider: Email
    to:
      - ysx20201030@163.com
    subject: '{{status}}: {{projectName}} {{buildVersion}}'                  # optional
    message: "Commit #{{commitId}} by {{commitAuthor}} on {{commitDate}}: {{commitMessage}}"    # optional
    on_build_success: true
    on_build_failure: false
    on_build_status_changed: false

