name: Windows

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release
  
permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest
    env:
      Qt_Dir_Static : D:/a/GenshinTianLiBattleClient/GenshinTianLiBattleClient/deps_qt/5.15.7/
      Opencv_Dir_Static : D:/a/GenshinTianLiBattleClient/GenshinTianLiBattleClient/opencv/
    steps:
    - uses: actions/checkout@v3
    
    - name: Clone Submodules
      env:
        CORE_TOKEN: ${{ secrets.GENSHINTIANLIBATTLECORE_PRIVATE }}
      run: |
        # secrets.GENSHINTIANLIBATTLECORE_PRIVATE 为私有令牌，用于访问私有仓库，需要在仓库的设置中添加
        # https://${CORE_TOKEN}@github.com/
        git user.name "GengGode"
        git user.token "${CORE_TOKEN}"
        git submodule update --init --recursive

    - name: Add Opencv
      run: |
        # 下载 https://github.com/GengGode/OpencvStaticLib/releases/download/4.6.0/Opencv.zip
        curl -L https://github.com/GengGode/OpencvStaticLib/releases/download/4.6.0/Opencv.zip -o Opencv.zip
        7z x Opencv.zip -oD:\a\GenshinTianLiBattleClient\GenshinTianLiBattleClient\opencv
        
    - name: Add Deps_Qt
      run: |
        git clone http://github.com/GenshinTianLiBattle/deps_qt.git
        cd deps_qt
        .\unzip.bat
        .\addpath.bat 
        dir
        dir ./openssl
        Copy-Item -Path "openssl" -Destination "C:\" -Recurse
        dir c:/
        cd ..
        copy deps_qt/QtMsBuild.7z GenshinTianLiBattleClient/
        copy deps_qt/7z.exe GenshinTianLiBattleClient/
        copy deps_qt/7z.dll GenshinTianLiBattleClient/
        cd GenshinTianLiBattleClient
        7z.exe x QtMsBuild.7z
        echo asd ${Qt_Dir_Static}
        
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
